name: inflearn-crawler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - requests==2.31.0
    - beautifulsoup4==4.12.2
    - selenium==4.15.0
    - python-multipart==0.0.6
    - jinja2==3.1.2
    - webdriver-manager==4.0.1